//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS4OldOA.TouchSMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sms.sysif.touch.com/api", ConfigurationName="TouchSMS.SmsMessageService")]
    public interface SmsMessageService {
        
        // CODEGEN: 消息 sendRequest 的包装命名空间(http://api.sms.sysif.touch.com)以后生成的消息协定与默认值(http://sms.sysif.touch.com/api)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SubSmsMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SmsReport))]
        SMS4OldOA.TouchSMS.sendResponse send(SMS4OldOA.TouchSMS.sendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.sendResponse> sendAsync(SMS4OldOA.TouchSMS.sendRequest request);
        
        // CODEGEN: 消息 batchSendRequest 的包装命名空间(http://api.sms.sysif.touch.com)以后生成的消息协定与默认值(http://sms.sysif.touch.com/api)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SubSmsMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SmsReport))]
        SMS4OldOA.TouchSMS.batchSendResponse batchSend(SMS4OldOA.TouchSMS.batchSendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.batchSendResponse> batchSendAsync(SMS4OldOA.TouchSMS.batchSendRequest request);
        
        // CODEGEN: 消息 getSmsReportsRequest 的包装命名空间(http://api.sms.sysif.touch.com)以后生成的消息协定与默认值(http://sms.sysif.touch.com/api)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SubSmsMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SmsReport))]
        SMS4OldOA.TouchSMS.getSmsReportsResponse getSmsReports(SMS4OldOA.TouchSMS.getSmsReportsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.getSmsReportsResponse> getSmsReportsAsync(SMS4OldOA.TouchSMS.getSmsReportsRequest request);
        
        // CODEGEN: 消息 getSmsMessageRequest 的包装命名空间(http://api.sms.sysif.touch.com)以后生成的消息协定与默认值(http://sms.sysif.touch.com/api)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SubSmsMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SmsReport))]
        SMS4OldOA.TouchSMS.getSmsMessageResponse getSmsMessage(SMS4OldOA.TouchSMS.getSmsMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.getSmsMessageResponse> getSmsMessageAsync(SMS4OldOA.TouchSMS.getSmsMessageRequest request);
        
        // CODEGEN: 消息 deliverSmsMessageRequest 的包装命名空间(http://api.sms.sysif.touch.com)以后生成的消息协定与默认值(http://sms.sysif.touch.com/api)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SubSmsMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SmsReport))]
        SMS4OldOA.TouchSMS.deliverSmsMessageResponse deliverSmsMessage(SMS4OldOA.TouchSMS.deliverSmsMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.deliverSmsMessageResponse> deliverSmsMessageAsync(SMS4OldOA.TouchSMS.deliverSmsMessageRequest request);
        
        // CODEGEN: 消息 deliverSmsReportsRequest 的包装命名空间(http://api.sms.sysif.touch.com)以后生成的消息协定与默认值(http://sms.sysif.touch.com/api)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SubSmsMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SmsReport))]
        SMS4OldOA.TouchSMS.deliverSmsReportsResponse deliverSmsReports(SMS4OldOA.TouchSMS.deliverSmsReportsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.deliverSmsReportsResponse> deliverSmsReportsAsync(SMS4OldOA.TouchSMS.deliverSmsReportsRequest request);
        
        // CODEGEN: 消息 activeTestRequest 的包装命名空间(http://api.sms.sysif.touch.com)以后生成的消息协定与默认值(http://sms.sysif.touch.com/api)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SubSmsMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SmsReport))]
        SMS4OldOA.TouchSMS.activeTestResponse activeTest(SMS4OldOA.TouchSMS.activeTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.activeTestResponse> activeTestAsync(SMS4OldOA.TouchSMS.activeTestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://sms.sysif.touch.com/api/model")]
    public partial class SmsMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string batchIdField;
        
        private string contentField;
        
        private string destAddrField;
        
        private System.Nullable<bool> reqReportField;
        
        private System.Nullable<System.DateTime> sendTimeField;
        
        private string smsParamField;
        
        private string sourceAddrField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string batchId {
            get {
                return this.batchIdField;
            }
            set {
                this.batchIdField = value;
                this.RaisePropertyChanged("batchId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string destAddr {
            get {
                return this.destAddrField;
            }
            set {
                this.destAddrField = value;
                this.RaisePropertyChanged("destAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<bool> reqReport {
            get {
                return this.reqReportField;
            }
            set {
                this.reqReportField = value;
                this.RaisePropertyChanged("reqReport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> sendTime {
            get {
                return this.sendTimeField;
            }
            set {
                this.sendTimeField = value;
                this.RaisePropertyChanged("sendTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string smsParam {
            get {
                return this.smsParamField;
            }
            set {
                this.smsParamField = value;
                this.RaisePropertyChanged("smsParam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sourceAddr {
            get {
                return this.sourceAddrField;
            }
            set {
                this.sourceAddrField = value;
                this.RaisePropertyChanged("sourceAddr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://sms.sysif.touch.com/api/model")]
    public partial class SubSmsMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string batchIdField;
        
        private string contentField;
        
        private string destAddrField;
        
        private System.Nullable<short> pkNumberField;
        
        private System.Nullable<short> pkTotalField;
        
        private string sourceAddrField;
        
        private int statusCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string batchId {
            get {
                return this.batchIdField;
            }
            set {
                this.batchIdField = value;
                this.RaisePropertyChanged("batchId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string destAddr {
            get {
                return this.destAddrField;
            }
            set {
                this.destAddrField = value;
                this.RaisePropertyChanged("destAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<short> pkNumber {
            get {
                return this.pkNumberField;
            }
            set {
                this.pkNumberField = value;
                this.RaisePropertyChanged("pkNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<short> pkTotal {
            get {
                return this.pkTotalField;
            }
            set {
                this.pkTotalField = value;
                this.RaisePropertyChanged("pkTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sourceAddr {
            get {
                return this.sourceAddrField;
            }
            set {
                this.sourceAddrField = value;
                this.RaisePropertyChanged("sourceAddr");
            }
        }
        
        /// <remarks/>
        public int statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://sms.sysif.touch.com/api/model")]
    public partial class SmsReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string batchIdField;
        
        private string destAddrField;
        
        private SubSmsMessage[] messageField;
        
        private System.Nullable<System.DateTime> receivedTimeField;
        
        private string sourceAddrField;
        
        private int statusCodeField;
        
        private string statusTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string batchId {
            get {
                return this.batchIdField;
            }
            set {
                this.batchIdField = value;
                this.RaisePropertyChanged("batchId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string destAddr {
            get {
                return this.destAddrField;
            }
            set {
                this.destAddrField = value;
                this.RaisePropertyChanged("destAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public SubSmsMessage[] message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> receivedTime {
            get {
                return this.receivedTimeField;
            }
            set {
                this.receivedTimeField = value;
                this.RaisePropertyChanged("receivedTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sourceAddr {
            get {
                return this.sourceAddrField;
            }
            set {
                this.sourceAddrField = value;
                this.RaisePropertyChanged("sourceAddr");
            }
        }
        
        /// <remarks/>
        public int statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string statusText {
            get {
                return this.statusTextField;
            }
            set {
                this.statusTextField = value;
                this.RaisePropertyChanged("statusText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send", WrapperNamespace="http://api.sms.sysif.touch.com", IsWrapped=true)]
    public partial class sendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public SMS4OldOA.TouchSMS.SmsMessage message;
        
        public sendRequest() {
        }
        
        public sendRequest(string username, string password, SMS4OldOA.TouchSMS.SmsMessage message) {
            this.username = username;
            this.password = password;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendResponse", WrapperNamespace="http://sms.sysif.touch.com/api", IsWrapped=true)]
    public partial class sendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sendReturn;
        
        public sendResponse() {
        }
        
        public sendResponse(string sendReturn) {
            this.sendReturn = sendReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="batchSend", WrapperNamespace="http://api.sms.sysif.touch.com", IsWrapped=true)]
    public partial class batchSendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public SMS4OldOA.TouchSMS.SmsMessage[] messages;
        
        public batchSendRequest() {
        }
        
        public batchSendRequest(string username, string password, SMS4OldOA.TouchSMS.SmsMessage[] messages) {
            this.username = username;
            this.password = password;
            this.messages = messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="batchSendResponse", WrapperNamespace="http://sms.sysif.touch.com/api", IsWrapped=true)]
    public partial class batchSendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string[] batchSendReturn;
        
        public batchSendResponse() {
        }
        
        public batchSendResponse(string[] batchSendReturn) {
            this.batchSendReturn = batchSendReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSmsReports", WrapperNamespace="http://api.sms.sysif.touch.com", IsWrapped=true)]
    public partial class getSmsReportsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string batchId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string destAddr;
        
        public getSmsReportsRequest() {
        }
        
        public getSmsReportsRequest(string username, string password, string batchId, string destAddr) {
            this.username = username;
            this.password = password;
            this.batchId = batchId;
            this.destAddr = destAddr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSmsReportsResponse", WrapperNamespace="http://sms.sysif.touch.com/api", IsWrapped=true)]
    public partial class getSmsReportsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public SMS4OldOA.TouchSMS.SmsReport[] getSmsReportsReturn;
        
        public getSmsReportsResponse() {
        }
        
        public getSmsReportsResponse(SMS4OldOA.TouchSMS.SmsReport[] getSmsReportsReturn) {
            this.getSmsReportsReturn = getSmsReportsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSmsMessage", WrapperNamespace="http://api.sms.sysif.touch.com", IsWrapped=true)]
    public partial class getSmsMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public getSmsMessageRequest() {
        }
        
        public getSmsMessageRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSmsMessageResponse", WrapperNamespace="http://sms.sysif.touch.com/api", IsWrapped=true)]
    public partial class getSmsMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public SMS4OldOA.TouchSMS.SmsMessage[] getSmsMessageReturn;
        
        public getSmsMessageResponse() {
        }
        
        public getSmsMessageResponse(SMS4OldOA.TouchSMS.SmsMessage[] getSmsMessageReturn) {
            this.getSmsMessageReturn = getSmsMessageReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deliverSmsMessage", WrapperNamespace="http://api.sms.sysif.touch.com", IsWrapped=true)]
    public partial class deliverSmsMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public SMS4OldOA.TouchSMS.SmsMessage[] messages;
        
        public deliverSmsMessageRequest() {
        }
        
        public deliverSmsMessageRequest(string username, string password, SMS4OldOA.TouchSMS.SmsMessage[] messages) {
            this.username = username;
            this.password = password;
            this.messages = messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deliverSmsMessageResponse", WrapperNamespace="http://sms.sysif.touch.com/api", IsWrapped=true)]
    public partial class deliverSmsMessageResponse {
        
        public deliverSmsMessageResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deliverSmsReports", WrapperNamespace="http://api.sms.sysif.touch.com", IsWrapped=true)]
    public partial class deliverSmsReportsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string batchId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public SMS4OldOA.TouchSMS.SmsReport[] reports;
        
        public deliverSmsReportsRequest() {
        }
        
        public deliverSmsReportsRequest(string username, string password, string batchId, SMS4OldOA.TouchSMS.SmsReport[] reports) {
            this.username = username;
            this.password = password;
            this.batchId = batchId;
            this.reports = reports;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deliverSmsReportsResponse", WrapperNamespace="http://sms.sysif.touch.com/api", IsWrapped=true)]
    public partial class deliverSmsReportsResponse {
        
        public deliverSmsReportsResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="activeTest", WrapperNamespace="http://api.sms.sysif.touch.com", IsWrapped=true)]
    public partial class activeTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public activeTestRequest() {
        }
        
        public activeTestRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="activeTestResponse", WrapperNamespace="http://sms.sysif.touch.com/api", IsWrapped=true)]
    public partial class activeTestResponse {
        
        public activeTestResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmsMessageServiceChannel : SMS4OldOA.TouchSMS.SmsMessageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsMessageServiceClient : System.ServiceModel.ClientBase<SMS4OldOA.TouchSMS.SmsMessageService>, SMS4OldOA.TouchSMS.SmsMessageService {
        
        public SmsMessageServiceClient() {
        }
        
        public SmsMessageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsMessageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsMessageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsMessageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS4OldOA.TouchSMS.sendResponse SMS4OldOA.TouchSMS.SmsMessageService.send(SMS4OldOA.TouchSMS.sendRequest request) {
            return base.Channel.send(request);
        }
        
        public string send(string username, string password, SMS4OldOA.TouchSMS.SmsMessage message) {
            SMS4OldOA.TouchSMS.sendRequest inValue = new SMS4OldOA.TouchSMS.sendRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.message = message;
            SMS4OldOA.TouchSMS.sendResponse retVal = ((SMS4OldOA.TouchSMS.SmsMessageService)(this)).send(inValue);
            return retVal.sendReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.sendResponse> SMS4OldOA.TouchSMS.SmsMessageService.sendAsync(SMS4OldOA.TouchSMS.sendRequest request) {
            return base.Channel.sendAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.sendResponse> sendAsync(string username, string password, SMS4OldOA.TouchSMS.SmsMessage message) {
            SMS4OldOA.TouchSMS.sendRequest inValue = new SMS4OldOA.TouchSMS.sendRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.message = message;
            return ((SMS4OldOA.TouchSMS.SmsMessageService)(this)).sendAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS4OldOA.TouchSMS.batchSendResponse SMS4OldOA.TouchSMS.SmsMessageService.batchSend(SMS4OldOA.TouchSMS.batchSendRequest request) {
            return base.Channel.batchSend(request);
        }
        
        public string[] batchSend(string username, string password, SMS4OldOA.TouchSMS.SmsMessage[] messages) {
            SMS4OldOA.TouchSMS.batchSendRequest inValue = new SMS4OldOA.TouchSMS.batchSendRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.messages = messages;
            SMS4OldOA.TouchSMS.batchSendResponse retVal = ((SMS4OldOA.TouchSMS.SmsMessageService)(this)).batchSend(inValue);
            return retVal.batchSendReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.batchSendResponse> SMS4OldOA.TouchSMS.SmsMessageService.batchSendAsync(SMS4OldOA.TouchSMS.batchSendRequest request) {
            return base.Channel.batchSendAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.batchSendResponse> batchSendAsync(string username, string password, SMS4OldOA.TouchSMS.SmsMessage[] messages) {
            SMS4OldOA.TouchSMS.batchSendRequest inValue = new SMS4OldOA.TouchSMS.batchSendRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.messages = messages;
            return ((SMS4OldOA.TouchSMS.SmsMessageService)(this)).batchSendAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS4OldOA.TouchSMS.getSmsReportsResponse SMS4OldOA.TouchSMS.SmsMessageService.getSmsReports(SMS4OldOA.TouchSMS.getSmsReportsRequest request) {
            return base.Channel.getSmsReports(request);
        }
        
        public SMS4OldOA.TouchSMS.SmsReport[] getSmsReports(string username, string password, string batchId, string destAddr) {
            SMS4OldOA.TouchSMS.getSmsReportsRequest inValue = new SMS4OldOA.TouchSMS.getSmsReportsRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.batchId = batchId;
            inValue.destAddr = destAddr;
            SMS4OldOA.TouchSMS.getSmsReportsResponse retVal = ((SMS4OldOA.TouchSMS.SmsMessageService)(this)).getSmsReports(inValue);
            return retVal.getSmsReportsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.getSmsReportsResponse> SMS4OldOA.TouchSMS.SmsMessageService.getSmsReportsAsync(SMS4OldOA.TouchSMS.getSmsReportsRequest request) {
            return base.Channel.getSmsReportsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.getSmsReportsResponse> getSmsReportsAsync(string username, string password, string batchId, string destAddr) {
            SMS4OldOA.TouchSMS.getSmsReportsRequest inValue = new SMS4OldOA.TouchSMS.getSmsReportsRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.batchId = batchId;
            inValue.destAddr = destAddr;
            return ((SMS4OldOA.TouchSMS.SmsMessageService)(this)).getSmsReportsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS4OldOA.TouchSMS.getSmsMessageResponse SMS4OldOA.TouchSMS.SmsMessageService.getSmsMessage(SMS4OldOA.TouchSMS.getSmsMessageRequest request) {
            return base.Channel.getSmsMessage(request);
        }
        
        public SMS4OldOA.TouchSMS.SmsMessage[] getSmsMessage(string username, string password) {
            SMS4OldOA.TouchSMS.getSmsMessageRequest inValue = new SMS4OldOA.TouchSMS.getSmsMessageRequest();
            inValue.username = username;
            inValue.password = password;
            SMS4OldOA.TouchSMS.getSmsMessageResponse retVal = ((SMS4OldOA.TouchSMS.SmsMessageService)(this)).getSmsMessage(inValue);
            return retVal.getSmsMessageReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.getSmsMessageResponse> SMS4OldOA.TouchSMS.SmsMessageService.getSmsMessageAsync(SMS4OldOA.TouchSMS.getSmsMessageRequest request) {
            return base.Channel.getSmsMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.getSmsMessageResponse> getSmsMessageAsync(string username, string password) {
            SMS4OldOA.TouchSMS.getSmsMessageRequest inValue = new SMS4OldOA.TouchSMS.getSmsMessageRequest();
            inValue.username = username;
            inValue.password = password;
            return ((SMS4OldOA.TouchSMS.SmsMessageService)(this)).getSmsMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS4OldOA.TouchSMS.deliverSmsMessageResponse SMS4OldOA.TouchSMS.SmsMessageService.deliverSmsMessage(SMS4OldOA.TouchSMS.deliverSmsMessageRequest request) {
            return base.Channel.deliverSmsMessage(request);
        }
        
        public void deliverSmsMessage(string username, string password, SMS4OldOA.TouchSMS.SmsMessage[] messages) {
            SMS4OldOA.TouchSMS.deliverSmsMessageRequest inValue = new SMS4OldOA.TouchSMS.deliverSmsMessageRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.messages = messages;
            SMS4OldOA.TouchSMS.deliverSmsMessageResponse retVal = ((SMS4OldOA.TouchSMS.SmsMessageService)(this)).deliverSmsMessage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.deliverSmsMessageResponse> SMS4OldOA.TouchSMS.SmsMessageService.deliverSmsMessageAsync(SMS4OldOA.TouchSMS.deliverSmsMessageRequest request) {
            return base.Channel.deliverSmsMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.deliverSmsMessageResponse> deliverSmsMessageAsync(string username, string password, SMS4OldOA.TouchSMS.SmsMessage[] messages) {
            SMS4OldOA.TouchSMS.deliverSmsMessageRequest inValue = new SMS4OldOA.TouchSMS.deliverSmsMessageRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.messages = messages;
            return ((SMS4OldOA.TouchSMS.SmsMessageService)(this)).deliverSmsMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS4OldOA.TouchSMS.deliverSmsReportsResponse SMS4OldOA.TouchSMS.SmsMessageService.deliverSmsReports(SMS4OldOA.TouchSMS.deliverSmsReportsRequest request) {
            return base.Channel.deliverSmsReports(request);
        }
        
        public void deliverSmsReports(string username, string password, string batchId, SMS4OldOA.TouchSMS.SmsReport[] reports) {
            SMS4OldOA.TouchSMS.deliverSmsReportsRequest inValue = new SMS4OldOA.TouchSMS.deliverSmsReportsRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.batchId = batchId;
            inValue.reports = reports;
            SMS4OldOA.TouchSMS.deliverSmsReportsResponse retVal = ((SMS4OldOA.TouchSMS.SmsMessageService)(this)).deliverSmsReports(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.deliverSmsReportsResponse> SMS4OldOA.TouchSMS.SmsMessageService.deliverSmsReportsAsync(SMS4OldOA.TouchSMS.deliverSmsReportsRequest request) {
            return base.Channel.deliverSmsReportsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.deliverSmsReportsResponse> deliverSmsReportsAsync(string username, string password, string batchId, SMS4OldOA.TouchSMS.SmsReport[] reports) {
            SMS4OldOA.TouchSMS.deliverSmsReportsRequest inValue = new SMS4OldOA.TouchSMS.deliverSmsReportsRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.batchId = batchId;
            inValue.reports = reports;
            return ((SMS4OldOA.TouchSMS.SmsMessageService)(this)).deliverSmsReportsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS4OldOA.TouchSMS.activeTestResponse SMS4OldOA.TouchSMS.SmsMessageService.activeTest(SMS4OldOA.TouchSMS.activeTestRequest request) {
            return base.Channel.activeTest(request);
        }
        
        public void activeTest(string username, string password) {
            SMS4OldOA.TouchSMS.activeTestRequest inValue = new SMS4OldOA.TouchSMS.activeTestRequest();
            inValue.username = username;
            inValue.password = password;
            SMS4OldOA.TouchSMS.activeTestResponse retVal = ((SMS4OldOA.TouchSMS.SmsMessageService)(this)).activeTest(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.activeTestResponse> SMS4OldOA.TouchSMS.SmsMessageService.activeTestAsync(SMS4OldOA.TouchSMS.activeTestRequest request) {
            return base.Channel.activeTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMS4OldOA.TouchSMS.activeTestResponse> activeTestAsync(string username, string password) {
            SMS4OldOA.TouchSMS.activeTestRequest inValue = new SMS4OldOA.TouchSMS.activeTestRequest();
            inValue.username = username;
            inValue.password = password;
            return ((SMS4OldOA.TouchSMS.SmsMessageService)(this)).activeTestAsync(inValue);
        }
    }
}
